NGC PyTorch 24.12 Dockerfile & requirements.txt (#305)
* NGC PyTorch 24.12 and requirements.txt

NGC PyTorch 24.12
 - Python 3.12
 - PyTorch 2.6
 - CUDA 12.6
and requirements.txt for NGC PyTorch 24.12

* modify installing dependencies
 - remove hwloc-like packages (Dependency conflict
  ImportError: /opt/hpcx/ucc/lib/libucc.so.1: undefined symbol issue)
 - kss (Dependency issue; python 3.12 doesn't support pyyaml 6.0,
   changed pyyaml version 6.0 to 6.0.2)

* fix to run Jupyter & Jupyter notebook for ngc-pytorch24.12
 - update Jupyter libraries

* fix jupyter call definition