modify installing dependencies
modify installing dependencies
 - remove hwloc-like packages (Dependency conflict
  ImportError: /opt/hpcx/ucc/lib/libucc.so.1: undefined symbol issue)
 - kss (Dependency issue; python 3.12 doesn't support pyyaml 6.0,
   changed pyyaml version 6.0 to 6.0.2)